# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'cameraScreen.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QGraphicsView,
    QGroupBox, QLabel, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)
import resources_rc

class Ui_cameraScreen(object):
    def setupUi(self, cameraScreen):
        if not cameraScreen.objectName():
            cameraScreen.setObjectName(u"cameraScreen")
        cameraScreen.resize(932, 651)
        cameraScreen.setStyleSheet(u"QWidget {\n"
"	color: #333;\n"
"	font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"	color: #000000;\n"
"	background-color: #ffffff;\n"
"	border: 1px solid #CCC;\n"
"	background-image: none;\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 2px solid rgb(154, 0, 0);\n"
"	text-align: left;\n"
"	padding-left: 8px;\n"
"	margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {\n"
"	background-color: #ffffff;\n"
"	border: 1px solid #CCC;\n"
"	color: #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"#leftMenuBg {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#topLogo {\n"
"	background-color: #000000;\n"
"	background-image: url(:/images/images"
                        "/images/GR_GJX.png);\n"
"	background-position: centered;\n"
"	background-repeat: no-repeat;\n"
"}\n"
"\n"
"#titleLeftApp {\n"
"	font: 63 12pt \"Segoe UI Semibold\";\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#titleLeftDescription {\n"
"	font: 8pt \"Segoe UI\";\n"
"	color: rgb(255, 109, 109);\n"
"}\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 22px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#topMenu .QPushButton:hover {\n"
"	background-color: #ff3a3a;\n"
"}\n"
"\n"
"#topMenu .QPushButton:pressed {\n"
"	background-color: rgb(255, 76, 76);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#bottomMenu .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 20px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	paddin"
                        "g-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#bottomMenu .QPushButton:hover {\n"
"	background-color: #ff3a3a;\n"
"}\n"
"\n"
"#bottomMenu .QPushButton:pressed {\n"
"	background-color: rgb(255, 49, 49);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#leftMenuFrame {\n"
"	border-top: 3px solid #000000;\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 20px solid transparent;\n"
"	background-color: #000000;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#toggleButton:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#toggleButton:pressed {\n"
"	background-color: rgb(255, 49, 49);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo {\n"
"	padding-left: 10px;\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Extra Tab */\n"
"#extraLeftBox {\n"
"	backg"
                        "round-color: #000000;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#extraTopBg {\n"
"	background-color: rgb(19, 19, 19)\n"
"}\n"
"\n"
"/* Icon */\n"
"#extraIcon {\n"
"	background-position: center;\n"
"	background-repeat: no-repeat;\n"
"	background-image: url(:/icons/images/icons/icon_settings.png);\n"
"}\n"
"\n"
"/* Label */\n"
"#extraLabel {\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Btn Close */\n"
"#extraCloseColumnBtn {\n"
"	background-color: rgba(255, 255, 255, 0);\n"
"	border: none;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"#extraCloseColumnBtn:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"#extraCloseColumnBtn:pressed {\n"
"	background-color: rgb(26, 26, 26);\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"/* Extra Content */\n"
"#extraContent {\n"
"	border-top: 3px solid #000000;\n"
"}\n"
"\n"
"/* Extra Top Menus */\n"
"#extraTopMenu .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
""
                        "	border: none;\n"
"	border-left: 22px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#extraTopMenu .QPushButton:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#extraTopMenu .QPushButton:pressed {\n"
"	background-color: rgb(19, 19, 19);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#contentBottom {\n"
"	border-top: 3px solid #000000;\n"
"}\n"
"\n"
"#titleRightInfo {\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"#rightButtons .QPushButton {\n"
"	background-color: rgba(255, 255, 255, 0);\n"
"	border: none;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"#rightButtons .QPushButton:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"#rightButtons .QPushButton:pressed {\n"
""
                        "	background-color: #ff4949;\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#themeSettingsTopDetail {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"/* Bottom Bar */\n"
"#bottomBar {\n"
"	background-color: #000000\n"
"}\n"
"\n"
"#bottomBar QLabel {\n"
"	font-size: 11px;\n"
"	color: #ffffff;\n"
"	padding-left: 10px;\n"
"	padding-right: 10px;\n"
"	padding-bottom: 2px;\n"
"}\n"
"\n"
"/* CONTENT SETTINGS */\n"
"/* MENUS */\n"
"#contentSettings .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 22px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#contentSettings .QPushButton:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#contentSettings .QPushButton:pressed {\n"
"	background-color: rgb(19, 19, 19);\n"
"	color: rgb(0, 0, 0);\n"
"}\n"
"\n"
""
                        "/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {\n"
"	background-color: transparent;\n"
"	padding: 10px;\n"
"	border-radius: 5px;\n"
"	gridline-color: #000000;\n"
"	outline: none;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"	border-color: #000000;\n"
"	padding-left: 5px;\n"
"	padding-right: 5px;\n"
"	gridline-color: #000000;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"	background-color: rgb(19, 19, 19);\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"	background-color: #000000;\n"
"	max-width: 30px;\n"
"	border: none;\n"
"	border-style: none;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"	border: 1px solid #000000;\n"
"	background-color: #000000;\n"
"	padding: 3px;\n"
"	border-top-left-radius: 7px;\n"
"	border-top-right-radius: 7px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"	border: 1px sol"
                        "id #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"	background-color: #000000;\n"
"	border-radius: 5px;\n"
"	border: 2px solid #000000;\n"
"	padding-left: 10px;\n"
"	selection-color: rgb(255, 255, 255);\n"
"	selection-background-color: rgb(255, 95, 95)rgb(255, 95, 95);\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"	border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"	background-color: #000000;\n"
"	border-radius: 5px;\n"
"	padding: 10px;\n"
"	selection-color: rgb(255, 255, 255);\n"
"	selection-background-color: rgb(255, 95, 95);\n"
"	color: #000000;\n"
"}\n"
"\n"
"QPlainTextEdit QScrollBar:vertical {\n"
"	width: 8px;\n"
"}\n"
"\n"
"QPlainTextEdit QScrollBar:horizontal {\n"
"	"
                        "height: 8px;\n"
"}\n"
"\n"
"QPlainTextEdit:hover {\n"
"	border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"	border: none;\n"
"	background: #000000;\n"
"	height: 8px;\n"
"	margin: 1px 21px 1px 21px;\n"
"	border-radius: px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"	background: rgb(19, 19, 19);\n"
"	min-width: 25px;\n"
"	border-radius: 4px\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"	border: none;\n"
"	background: #000000;\n"
"	width: 20px;\n"
"	border-top-right-radius: 4px;\n"
"	border-bottom-right-radius: 4px;\n"
"	subcontrol-position: right;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"	border: none;\n"
"	background: #000000;\n"
"	width: 20px;\n"
"	border-top-left-radius: 4px;\n"
"	border-bottom-left-radius: 4px;\n"
"	subcontrol-p"
                        "osition: left;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"	background: #000000;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"	background: #000000;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"	border: none;\n"
"	background-color: #000000;\n"
"	width: 8px;\n"
"	margin: 21px 0 21px 0;\n"
"	border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"	background: #000000;\n"
"	min-height: 25px;\n"
"	border-radius: 4px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"	border: none;\n"
"	background: #000000;\n"
"	height: 20px;\n"
"	border-bottom-left-radius: 4px;\n"
"	border-bottom-right-radius: 4px;\n"
"	subcontrol-position: bottom;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"	border: none;\n"
"	background: #000000;\n"
"	height: 20px;\n"
"	border-top-left-radius: 4px;\n"
"	border-top-right-radius: 4px;\n"
"	subcontrol-position: top;\n"
"	subcontr"
                        "ol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"	background: #000000;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"	background: #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"	border: 3px solid #000000;\n"
"	width: 15px;\n"
"	height: 15px;\n"
"	border-radius: 10px;\n"
"	background: #000000;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"	border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"	background: 3px solid #ff3a3a;\n"
"	border: 3px solid #000000;\n"
"	background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"	border: 3px solid #000000;\n"
"	width: 15px;\n"
"	height: 15px;\n"
"	border"
                        "-radius: 10px;\n"
"	background: #000000;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"	border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"	background: 3px solid #ff3a3a;\n"
"	border: 3px solid #ff3a3a;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox {\n"
"	background-color: #000000;\n"
"	border-radius: 5px;\n"
"	border: 2px solid #000000;\n"
"	padding: 5px;\n"
"	padding-left: 10px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"	border: 2px solid #000000;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"	subcontrol-origin: padding;\n"
"	subcontrol-position: top right;\n"
"	width: 25px;\n"
"	border-left-width: 3px;\n"
"	border-left-color: #000000;\n"
"	border-left-style: solid;\n"
"	border-top-right-radius: 3px;\n"
"	border-bottom-right-radius: 3px;\n"
"	background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"	background-position: center;\n"
"	background-rep"
                        "eat: no-reperat;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"	color: rgb(255, 95, 95);\n"
"	background-color: #000000;\n"
"	padding: 10px;\n"
"	selection-background-color: #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"	border-radius: 5px;\n"
"	height: 10px;\n"
"	margin: 0px;\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"	background-color: rgb(19, 19, 19);\n"
"	border: none;\n"
"	height: 10px;\n"
"	width: 10px;\n"
"	margin: 0px;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"	background-color: rgb(255, 95, 95);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"	border-radius: 5px;\n"
"	width: 10px;\n"
"	margin: 0px;\n"
"	background-color: #000000;\n"
""
                        "}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"	background-color: rgb(19, 19, 19);\n"
"	border: none;\n"
"	height: 10px;\n"
"	width: 10px;\n"
"	margin: 0px;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"	background-color: rgb(255, 95, 95);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"#pagesContainer QCommandLinkButton {\n"
"	color: rgb(255, 95, 95);\n"
"	border-radius: 5px;\n"
"	padding: 5px;\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"	color: rgb(255, 49, 49);\n"
"}\n"
"\n"
"#pagesContainer QCommandLinkButton:hover {\n"
"	color: rgb(255, 128, 128);\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#pagesContainer QCommandLinkButton:pressed {\n"
"	color: rgb(19, 19, 19);\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"/* ////"
                        "/////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"#pagesContainer QPushButton {\n"
"	border: 2px solid #000000;\n"
"	border-radius: 5px;\n"
"	background-color: #000000;\n"
"	color: #000000;\n"
"}\n"
"\n"
"#pagesContainer QPushButton:hover {\n"
"	background-color: #000000;\n"
"	border: 2px solid #000000;\n"
"}\n"
"\n"
"#pagesContainer QPushButton:pressed {\n"
"	background-color: #000000;\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}")
        self.centralwidget = QWidget(cameraScreen)
        self.centralwidget.setObjectName(u"centralwidget")
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(10, 40, 683, 512))
        self.graphicsView.setDragMode(QGraphicsView.ScrollHandDrag)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(700, 0, 221, 171))
        self.groupBox.setStyleSheet(u"QWidget {\n"
"	color: #333;\n"
"	font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"	color: #000000;\n"
"	background-color: #ffffff;\n"
"	border: 1px solid #CCC;\n"
"	background-image: none;\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 2px solid rgb(154, 0, 0);\n"
"	text-align: left;\n"
"	padding-left: 8px;\n"
"	margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {\n"
"	background-color: #ffffff;\n"
"	border: 1px solid #CCC;\n"
"	color: #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"#leftMenuBg {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#topLogo {\n"
"	background-color: #000000;\n"
"	background-image: url(:/images/images"
                        "/images/GR_GJX.png);\n"
"	background-position: centered;\n"
"	background-repeat: no-repeat;\n"
"}\n"
"\n"
"#titleLeftApp {\n"
"	font: 63 12pt \"Segoe UI Semibold\";\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#titleLeftDescription {\n"
"	font: 8pt \"Segoe UI\";\n"
"	color: rgb(255, 109, 109);\n"
"}\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 22px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#topMenu .QPushButton:hover {\n"
"	background-color: #ff3a3a;\n"
"}\n"
"\n"
"#topMenu .QPushButton:pressed {\n"
"	background-color: rgb(255, 76, 76);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#bottomMenu .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 20px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	paddin"
                        "g-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#bottomMenu .QPushButton:hover {\n"
"	background-color: #ff3a3a;\n"
"}\n"
"\n"
"#bottomMenu .QPushButton:pressed {\n"
"	background-color: rgb(255, 49, 49);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#leftMenuFrame {\n"
"	border-top: 3px solid #000000;\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 20px solid transparent;\n"
"	background-color: #000000;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#toggleButton:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#toggleButton:pressed {\n"
"	background-color: rgb(255, 49, 49);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo {\n"
"	padding-left: 10px;\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Extra Tab */\n"
"#extraLeftBox {\n"
"	backg"
                        "round-color: #000000;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#extraTopBg {\n"
"	background-color: rgb(19, 19, 19)\n"
"}\n"
"\n"
"/* Icon */\n"
"#extraIcon {\n"
"	background-position: center;\n"
"	background-repeat: no-repeat;\n"
"	background-image: url(:/icons/images/icons/icon_settings.png);\n"
"}\n"
"\n"
"/* Label */\n"
"#extraLabel {\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Btn Close */\n"
"#extraCloseColumnBtn {\n"
"	background-color: rgba(255, 255, 255, 0);\n"
"	border: none;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"#extraCloseColumnBtn:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"#extraCloseColumnBtn:pressed {\n"
"	background-color: rgb(26, 26, 26);\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"/* Extra Content */\n"
"#extraContent {\n"
"	border-top: 3px solid #000000;\n"
"}\n"
"\n"
"/* Extra Top Menus */\n"
"#extraTopMenu .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
""
                        "	border: none;\n"
"	border-left: 22px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#extraTopMenu .QPushButton:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#extraTopMenu .QPushButton:pressed {\n"
"	background-color: rgb(19, 19, 19);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#contentBottom {\n"
"	border-top: 3px solid #000000;\n"
"}\n"
"\n"
"#titleRightInfo {\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"#rightButtons .QPushButton {\n"
"	background-color: rgba(255, 255, 255, 0);\n"
"	border: none;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"#rightButtons .QPushButton:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"#rightButtons .QPushButton:pressed {\n"
""
                        "	background-color: #ff4949;\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#themeSettingsTopDetail {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"/* Bottom Bar */\n"
"#bottomBar {\n"
"	background-color: #000000\n"
"}\n"
"\n"
"#bottomBar QLabel {\n"
"	font-size: 11px;\n"
"	color: #ffffff;\n"
"	padding-left: 10px;\n"
"	padding-right: 10px;\n"
"	padding-bottom: 2px;\n"
"}\n"
"\n"
"/* CONTENT SETTINGS */\n"
"/* MENUS */\n"
"#contentSettings .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 22px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#contentSettings .QPushButton:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#contentSettings .QPushButton:pressed {\n"
"	background-color: rgb(19, 19, 19);\n"
"	color: rgb(0, 0, 0);\n"
"}\n"
"\n"
""
                        "/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {\n"
"	background-color: transparent;\n"
"	padding: 10px;\n"
"	border-radius: 5px;\n"
"	gridline-color: #000000;\n"
"	outline: none;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"	border-color: #000000;\n"
"	padding-left: 5px;\n"
"	padding-right: 5px;\n"
"	gridline-color: #000000;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"	background-color: rgb(19, 19, 19);\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"	background-color: #000000;\n"
"	max-width: 30px;\n"
"	border: none;\n"
"	border-style: none;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"	border: 1px solid #000000;\n"
"	background-color: #000000;\n"
"	padding: 3px;\n"
"	border-top-left-radius: 7px;\n"
"	border-top-right-radius: 7px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"	border: 1px sol"
                        "id #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"	background-color: #000000;\n"
"	border-radius: 5px;\n"
"	border: 2px solid #000000;\n"
"	padding-left: 10px;\n"
"	selection-color: rgb(255, 255, 255);\n"
"	selection-background-color: rgb(255, 95, 95)rgb(255, 95, 95);\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"	border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"	background-color: #000000;\n"
"	border-radius: 5px;\n"
"	padding: 10px;\n"
"	selection-color: rgb(255, 255, 255);\n"
"	selection-background-color: rgb(255, 95, 95);\n"
"	color: #000000;\n"
"}\n"
"\n"
"QPlainTextEdit QScrollBar:vertical {\n"
"	width: 8px;\n"
"}\n"
"\n"
"QPlainTextEdit QScrollBar:horizontal {\n"
"	"
                        "height: 8px;\n"
"}\n"
"\n"
"QPlainTextEdit:hover {\n"
"	border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"	border: none;\n"
"	background: #000000;\n"
"	height: 8px;\n"
"	margin: 1px 21px 1px 21px;\n"
"	border-radius: px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"	background: rgb(19, 19, 19);\n"
"	min-width: 25px;\n"
"	border-radius: 4px\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"	border: none;\n"
"	background: #000000;\n"
"	width: 20px;\n"
"	border-top-right-radius: 4px;\n"
"	border-bottom-right-radius: 4px;\n"
"	subcontrol-position: right;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"	border: none;\n"
"	background: #000000;\n"
"	width: 20px;\n"
"	border-top-left-radius: 4px;\n"
"	border-bottom-left-radius: 4px;\n"
"	subcontrol-p"
                        "osition: left;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"	background: #000000;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"	background: #000000;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"	border: none;\n"
"	background-color: #000000;\n"
"	width: 8px;\n"
"	margin: 21px 0 21px 0;\n"
"	border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"	background: #000000;\n"
"	min-height: 25px;\n"
"	border-radius: 4px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"	border: none;\n"
"	background: #000000;\n"
"	height: 20px;\n"
"	border-bottom-left-radius: 4px;\n"
"	border-bottom-right-radius: 4px;\n"
"	subcontrol-position: bottom;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"	border: none;\n"
"	background: #000000;\n"
"	height: 20px;\n"
"	border-top-left-radius: 4px;\n"
"	border-top-right-radius: 4px;\n"
"	subcontrol-position: top;\n"
"	subcontr"
                        "ol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"	background: #000000;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"	background: #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"	border: 3px solid #000000;\n"
"	width: 15px;\n"
"	height: 15px;\n"
"	border-radius: 10px;\n"
"	background: #000000;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"	border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"	background: 3px solid #ff3a3a;\n"
"	border: 3px solid #000000;\n"
"	background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"	border: 3px solid #000000;\n"
"	width: 15px;\n"
"	height: 15px;\n"
"	border"
                        "-radius: 10px;\n"
"	background: #000000;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"	border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"	background: 3px solid #ff3a3a;\n"
"	border: 3px solid #ff3a3a;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox {\n"
"	background-color: #000000;\n"
"	border-radius: 5px;\n"
"	border: 2px solid #000000;\n"
"	padding: 5px;\n"
"	padding-left: 10px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"	border: 2px solid #000000;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"	subcontrol-origin: padding;\n"
"	subcontrol-position: top right;\n"
"	width: 25px;\n"
"	border-left-width: 3px;\n"
"	border-left-color: #000000;\n"
"	border-left-style: solid;\n"
"	border-top-right-radius: 3px;\n"
"	border-bottom-right-radius: 3px;\n"
"	background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"	background-position: center;\n"
"	background-rep"
                        "eat: no-reperat;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"	color: rgb(255, 95, 95);\n"
"	background-color: #000000;\n"
"	padding: 10px;\n"
"	selection-background-color: #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"	border-radius: 5px;\n"
"	height: 10px;\n"
"	margin: 0px;\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"	background-color: rgb(19, 19, 19);\n"
"	border: none;\n"
"	height: 10px;\n"
"	width: 10px;\n"
"	margin: 0px;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"	background-color: rgb(255, 95, 95);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"	border-radius: 5px;\n"
"	width: 10px;\n"
"	margin: 0px;\n"
"	background-color: #000000;\n"
""
                        "}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"	background-color: rgb(19, 19, 19);\n"
"	border: none;\n"
"	height: 10px;\n"
"	width: 10px;\n"
"	margin: 0px;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"	background-color: rgb(255, 95, 95);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"#pagesContainer QCommandLinkButton {\n"
"	color: rgb(255, 95, 95);\n"
"	border-radius: 5px;\n"
"	padding: 5px;\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"	color: rgb(255, 49, 49);\n"
"}\n"
"\n"
"#pagesContainer QCommandLinkButton:hover {\n"
"	color: rgb(255, 128, 128);\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#pagesContainer QCommandLinkButton:pressed {\n"
"	color: rgb(19, 19, 19);\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"/* ////"
                        "/////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"#pagesContainer QPushButton {\n"
"	border: 2px solid #000000;\n"
"	border-radius: 5px;\n"
"	background-color: #000000;\n"
"	color: #000000;\n"
"}\n"
"\n"
"#pagesContainer QPushButton:hover {\n"
"	background-color: #000000;\n"
"	border: 2px solid #000000;\n"
"}\n"
"\n"
"#pagesContainer QPushButton:pressed {\n"
"	background-color: #000000;\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}")
        self.comboBox_CameraList = QComboBox(self.groupBox)
        self.comboBox_CameraList.setObjectName(u"comboBox_CameraList")
        self.comboBox_CameraList.setGeometry(QRect(10, 70, 201, 31))
        self.pushButton_UpdateCameraList = QPushButton(self.groupBox)
        self.pushButton_UpdateCameraList.setObjectName(u"pushButton_UpdateCameraList")
        self.pushButton_UpdateCameraList.setGeometry(QRect(10, 30, 201, 31))
        self.pushButton_OpenCamera = QPushButton(self.groupBox)
        self.pushButton_OpenCamera.setObjectName(u"pushButton_OpenCamera")
        self.pushButton_OpenCamera.setGeometry(QRect(10, 110, 101, 28))
        self.pushButton_CloseCamera = QPushButton(self.groupBox)
        self.pushButton_CloseCamera.setObjectName(u"pushButton_CloseCamera")
        self.pushButton_CloseCamera.setGeometry(QRect(110, 110, 101, 28))
        self.pushButton_CloseCamera.setStyleSheet(u"QWidget {\n"
"	color: #333;\n"
"	font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"	color: #000000;\n"
"	background-color: #ffffff;\n"
"	border: 1px solid #CCC;\n"
"	background-image: none;\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 2px solid rgb(154, 0, 0);\n"
"	text-align: left;\n"
"	padding-left: 8px;\n"
"	margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {\n"
"	background-color: #ffffff;\n"
"	border: 1px solid #CCC;\n"
"	color: #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"#leftMenuBg {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#topLogo {\n"
"	background-color: #000000;\n"
"	background-image: url(:/images/images"
                        "/images/GR_GJX.png);\n"
"	background-position: centered;\n"
"	background-repeat: no-repeat;\n"
"}\n"
"\n"
"#titleLeftApp {\n"
"	font: 63 12pt \"Segoe UI Semibold\";\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#titleLeftDescription {\n"
"	font: 8pt \"Segoe UI\";\n"
"	color: rgb(255, 109, 109);\n"
"}\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 22px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#topMenu .QPushButton:hover {\n"
"	background-color: #ff3a3a;\n"
"}\n"
"\n"
"#topMenu .QPushButton:pressed {\n"
"	background-color: rgb(255, 76, 76);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#bottomMenu .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 20px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	paddin"
                        "g-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#bottomMenu .QPushButton:hover {\n"
"	background-color: #ff3a3a;\n"
"}\n"
"\n"
"#bottomMenu .QPushButton:pressed {\n"
"	background-color: rgb(255, 49, 49);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#leftMenuFrame {\n"
"	border-top: 3px solid #000000;\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 20px solid transparent;\n"
"	background-color: #000000;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#toggleButton:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#toggleButton:pressed {\n"
"	background-color: rgb(255, 49, 49);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo {\n"
"	padding-left: 10px;\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Extra Tab */\n"
"#extraLeftBox {\n"
"	backg"
                        "round-color: #000000;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#extraTopBg {\n"
"	background-color: rgb(19, 19, 19)\n"
"}\n"
"\n"
"/* Icon */\n"
"#extraIcon {\n"
"	background-position: center;\n"
"	background-repeat: no-repeat;\n"
"	background-image: url(:/icons/images/icons/icon_settings.png);\n"
"}\n"
"\n"
"/* Label */\n"
"#extraLabel {\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Btn Close */\n"
"#extraCloseColumnBtn {\n"
"	background-color: rgba(255, 255, 255, 0);\n"
"	border: none;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"#extraCloseColumnBtn:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"#extraCloseColumnBtn:pressed {\n"
"	background-color: rgb(26, 26, 26);\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"/* Extra Content */\n"
"#extraContent {\n"
"	border-top: 3px solid #000000;\n"
"}\n"
"\n"
"/* Extra Top Menus */\n"
"#extraTopMenu .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
""
                        "	border: none;\n"
"	border-left: 22px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#extraTopMenu .QPushButton:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#extraTopMenu .QPushButton:pressed {\n"
"	background-color: rgb(19, 19, 19);\n"
"	color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#contentBottom {\n"
"	border-top: 3px solid #000000;\n"
"}\n"
"\n"
"#titleRightInfo {\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"#rightButtons .QPushButton {\n"
"	background-color: rgba(255, 255, 255, 0);\n"
"	border: none;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"#rightButtons .QPushButton:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"#rightButtons .QPushButton:pressed {\n"
""
                        "	background-color: #ff4949;\n"
"	border-style: solid;\n"
"	border-radius: 4px;\n"
"}\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#themeSettingsTopDetail {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"/* Bottom Bar */\n"
"#bottomBar {\n"
"	background-color: #000000\n"
"}\n"
"\n"
"#bottomBar QLabel {\n"
"	font-size: 11px;\n"
"	color: #ffffff;\n"
"	padding-left: 10px;\n"
"	padding-right: 10px;\n"
"	padding-bottom: 2px;\n"
"}\n"
"\n"
"/* CONTENT SETTINGS */\n"
"/* MENUS */\n"
"#contentSettings .QPushButton {\n"
"	background-position: left center;\n"
"	background-repeat: no-repeat;\n"
"	border: none;\n"
"	border-left: 22px solid transparent;\n"
"	background-color: transparent;\n"
"	text-align: left;\n"
"	padding-left: 44px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"#contentSettings .QPushButton:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#contentSettings .QPushButton:pressed {\n"
"	background-color: rgb(19, 19, 19);\n"
"	color: rgb(0, 0, 0);\n"
"}\n"
"\n"
""
                        "/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {\n"
"	background-color: transparent;\n"
"	padding: 10px;\n"
"	border-radius: 5px;\n"
"	gridline-color: #000000;\n"
"	outline: none;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"	border-color: #000000;\n"
"	padding-left: 5px;\n"
"	padding-right: 5px;\n"
"	gridline-color: #000000;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"	background-color: rgb(19, 19, 19);\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"	background-color: #000000;\n"
"	max-width: 30px;\n"
"	border: none;\n"
"	border-style: none;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"	border: 1px solid #000000;\n"
"	background-color: #000000;\n"
"	padding: 3px;\n"
"	border-top-left-radius: 7px;\n"
"	border-top-right-radius: 7px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"	border: 1px sol"
                        "id #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"	background-color: #000000;\n"
"	border-radius: 5px;\n"
"	border: 2px solid #000000;\n"
"	padding-left: 10px;\n"
"	selection-color: rgb(255, 255, 255);\n"
"	selection-background-color: rgb(255, 95, 95)rgb(255, 95, 95);\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"	border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"	background-color: #000000;\n"
"	border-radius: 5px;\n"
"	padding: 10px;\n"
"	selection-color: rgb(255, 255, 255);\n"
"	selection-background-color: rgb(255, 95, 95);\n"
"	color: #000000;\n"
"}\n"
"\n"
"QPlainTextEdit QScrollBar:vertical {\n"
"	width: 8px;\n"
"}\n"
"\n"
"QPlainTextEdit QScrollBar:horizontal {\n"
"	"
                        "height: 8px;\n"
"}\n"
"\n"
"QPlainTextEdit:hover {\n"
"	border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"	border: none;\n"
"	background: #000000;\n"
"	height: 8px;\n"
"	margin: 1px 21px 1px 21px;\n"
"	border-radius: px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"	background: rgb(19, 19, 19);\n"
"	min-width: 25px;\n"
"	border-radius: 4px\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"	border: none;\n"
"	background: #000000;\n"
"	width: 20px;\n"
"	border-top-right-radius: 4px;\n"
"	border-bottom-right-radius: 4px;\n"
"	subcontrol-position: right;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"	border: none;\n"
"	background: #000000;\n"
"	width: 20px;\n"
"	border-top-left-radius: 4px;\n"
"	border-bottom-left-radius: 4px;\n"
"	subcontrol-p"
                        "osition: left;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"	background: #000000;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"	background: #000000;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"	border: none;\n"
"	background-color: #000000;\n"
"	width: 8px;\n"
"	margin: 21px 0 21px 0;\n"
"	border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"	background: #000000;\n"
"	min-height: 25px;\n"
"	border-radius: 4px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"	border: none;\n"
"	background: #000000;\n"
"	height: 20px;\n"
"	border-bottom-left-radius: 4px;\n"
"	border-bottom-right-radius: 4px;\n"
"	subcontrol-position: bottom;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"	border: none;\n"
"	background: #000000;\n"
"	height: 20px;\n"
"	border-top-left-radius: 4px;\n"
"	border-top-right-radius: 4px;\n"
"	subcontrol-position: top;\n"
"	subcontr"
                        "ol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"	background: #000000;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"	background: #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"	border: 3px solid #000000;\n"
"	width: 15px;\n"
"	height: 15px;\n"
"	border-radius: 10px;\n"
"	background: #000000;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"	border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"	background: 3px solid #ff3a3a;\n"
"	border: 3px solid #000000;\n"
"	background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"	border: 3px solid #000000;\n"
"	width: 15px;\n"
"	height: 15px;\n"
"	border"
                        "-radius: 10px;\n"
"	background: #000000;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"	border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"	background: 3px solid #ff3a3a;\n"
"	border: 3px solid #ff3a3a;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox {\n"
"	background-color: #000000;\n"
"	border-radius: 5px;\n"
"	border: 2px solid #000000;\n"
"	padding: 5px;\n"
"	padding-left: 10px;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"	border: 2px solid #000000;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"	subcontrol-origin: padding;\n"
"	subcontrol-position: top right;\n"
"	width: 25px;\n"
"	border-left-width: 3px;\n"
"	border-left-color: #000000;\n"
"	border-left-style: solid;\n"
"	border-top-right-radius: 3px;\n"
"	border-bottom-right-radius: 3px;\n"
"	background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"	background-position: center;\n"
"	background-rep"
                        "eat: no-reperat;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"	color: rgb(255, 95, 95);\n"
"	background-color: #000000;\n"
"	padding: 10px;\n"
"	selection-background-color: #000000;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"	border-radius: 5px;\n"
"	height: 10px;\n"
"	margin: 0px;\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"	background-color: rgb(19, 19, 19);\n"
"	border: none;\n"
"	height: 10px;\n"
"	width: 10px;\n"
"	margin: 0px;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"	background-color: rgb(255, 95, 95);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"	border-radius: 5px;\n"
"	width: 10px;\n"
"	margin: 0px;\n"
"	background-color: #000000;\n"
""
                        "}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"	background-color: rgb(19, 19, 19);\n"
"	border: none;\n"
"	height: 10px;\n"
"	width: 10px;\n"
"	margin: 0px;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"	background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"	background-color: rgb(255, 95, 95);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"#pagesContainer QCommandLinkButton {\n"
"	color: rgb(255, 95, 95);\n"
"	border-radius: 5px;\n"
"	padding: 5px;\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"	color: rgb(255, 49, 49);\n"
"}\n"
"\n"
"#pagesContainer QCommandLinkButton:hover {\n"
"	color: rgb(255, 128, 128);\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"#pagesContainer QCommandLinkButton:pressed {\n"
"	color: rgb(19, 19, 19);\n"
"	background-color: #000000;\n"
"}\n"
"\n"
"/* ////"
                        "/////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"#pagesContainer QPushButton {\n"
"	border: 2px solid #000000;\n"
"	border-radius: 5px;\n"
"	background-color: #000000;\n"
"	color: #000000;\n"
"}\n"
"\n"
"#pagesContainer QPushButton:hover {\n"
"	background-color: #000000;\n"
"	border: 2px solid #000000;\n"
"}\n"
"\n"
"#pagesContainer QPushButton:pressed {\n"
"	background-color: #000000;\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}")
        self.pushButton_StartAcq = QPushButton(self.groupBox)
        self.pushButton_StartAcq.setObjectName(u"pushButton_StartAcq")
        self.pushButton_StartAcq.setGeometry(QRect(10, 140, 101, 28))
        self.pushButton_StartAcq.setStyleSheet(u"\n"
"#pagesContainer QPushButton {\n"
"	border: 2px solid #000000;\n"
"	border-radius: 5px;\n"
"	background-color: #000000;\n"
"	color: #000000;\n"
"}\n"
"\n"
"#pagesContainer QPushButton:hover {\n"
"	background-color: #000000;\n"
"	border: 2px solid #000000;\n"
"}\n"
"\n"
"#pagesContainer QPushButton:pressed {\n"
"	background-color: #000000;\n"
"	border: 2px solid rgb(255, 49, 49);\n"
"}")
        self.pushButton_StopAcq = QPushButton(self.groupBox)
        self.pushButton_StopAcq.setObjectName(u"pushButton_StopAcq")
        self.pushButton_StopAcq.setGeometry(QRect(110, 140, 101, 28))
        self.pushButton_ZoomIn = QPushButton(self.centralwidget)
        self.pushButton_ZoomIn.setObjectName(u"pushButton_ZoomIn")
        self.pushButton_ZoomIn.setGeometry(QRect(510, 10, 92, 28))
        self.pushButton_ZoomOut = QPushButton(self.centralwidget)
        self.pushButton_ZoomOut.setObjectName(u"pushButton_ZoomOut")
        self.pushButton_ZoomOut.setGeometry(QRect(600, 10, 92, 28))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(700, 170, 221, 111))
        self.comboBox_ExposureMode = QComboBox(self.groupBox_2)
        self.comboBox_ExposureMode.setObjectName(u"comboBox_ExposureMode")
        self.comboBox_ExposureMode.setGeometry(QRect(120, 20, 91, 22))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 111, 21))
        self.comboBox_ExposureAuto = QComboBox(self.groupBox_2)
        self.comboBox_ExposureAuto.setObjectName(u"comboBox_ExposureAuto")
        self.comboBox_ExposureAuto.setGeometry(QRect(120, 50, 91, 22))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 111, 21))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 80, 111, 21))
        self.doubleSpinBox_ExposureTime = QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_ExposureTime.setObjectName(u"doubleSpinBox_ExposureTime")
        self.doubleSpinBox_ExposureTime.setGeometry(QRect(120, 80, 91, 22))
        self.doubleSpinBox_ExposureTime.setMaximum(99999999.989999994635582)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 560, 72, 15))
        self.label_AcqNum = QLabel(self.centralwidget)
        self.label_AcqNum.setObjectName(u"label_AcqNum")
        self.label_AcqNum.setGeometry(QRect(80, 560, 72, 15))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(180, 560, 41, 16))
        self.label_FPS = QLabel(self.centralwidget)
        self.label_FPS.setObjectName(u"label_FPS")
        self.label_FPS.setGeometry(QRect(220, 560, 41, 16))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(700, 280, 221, 131))
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 20, 111, 21))
        self.comboBox_TriggerMode = QComboBox(self.groupBox_3)
        self.comboBox_TriggerMode.setObjectName(u"comboBox_TriggerMode")
        self.comboBox_TriggerMode.setGeometry(QRect(120, 20, 91, 22))
        self.comboBox_TriggerSource = QComboBox(self.groupBox_3)
        self.comboBox_TriggerSource.setObjectName(u"comboBox_TriggerSource")
        self.comboBox_TriggerSource.setGeometry(QRect(120, 50, 91, 22))
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 50, 111, 21))
        self.pushButton_SendSoftwareCommand = QPushButton(self.groupBox_3)
        self.pushButton_SendSoftwareCommand.setObjectName(u"pushButton_SendSoftwareCommand")
        self.pushButton_SendSoftwareCommand.setGeometry(QRect(10, 80, 201, 41))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(700, 410, 221, 81))
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 20, 111, 21))
        self.comboBox_GainAuto = QComboBox(self.groupBox_4)
        self.comboBox_GainAuto.setObjectName(u"comboBox_GainAuto")
        self.comboBox_GainAuto.setGeometry(QRect(120, 20, 91, 22))
        self.doubleSpinBox_GainValue = QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_GainValue.setObjectName(u"doubleSpinBox_GainValue")
        self.doubleSpinBox_GainValue.setGeometry(QRect(120, 50, 91, 22))
        self.doubleSpinBox_GainValue.setMaximum(99999999.989999994635582)
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 50, 111, 21))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(700, 490, 221, 61))
        cameraScreen.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(cameraScreen)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 932, 24))
        cameraScreen.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(cameraScreen)
        self.statusbar.setObjectName(u"statusbar")
        cameraScreen.setStatusBar(self.statusbar)

        self.retranslateUi(cameraScreen)
        self.pushButton.clicked.connect(cameraScreen.close)

        QMetaObject.connectSlotsByName(cameraScreen)
    # setupUi

    def retranslateUi(self, cameraScreen):
        cameraScreen.setWindowTitle(QCoreApplication.translate("cameraScreen", u"\u76f8\u673a\u63a7\u5236\u7cfb\u7edf", None))
        self.groupBox.setTitle(QCoreApplication.translate("cameraScreen", u"\u76f8\u673a\u63a7\u5236", None))
        self.pushButton_UpdateCameraList.setText(QCoreApplication.translate("cameraScreen", u"\u66f4\u65b0\u76f8\u673a\u5217\u8868", None))
        self.pushButton_OpenCamera.setText(QCoreApplication.translate("cameraScreen", u"\u6253\u5f00\u76f8\u673a", None))
        self.pushButton_CloseCamera.setText(QCoreApplication.translate("cameraScreen", u"\u5173\u95ed\u76f8\u673a", None))
        self.pushButton_StartAcq.setText(QCoreApplication.translate("cameraScreen", u"\u5f00\u59cb\u91c7\u96c6", None))
        self.pushButton_StopAcq.setText(QCoreApplication.translate("cameraScreen", u"\u505c\u6b62\u91c7\u96c6", None))
        self.pushButton_ZoomIn.setText(QCoreApplication.translate("cameraScreen", u"\u7f29\u5c0f", None))
        self.pushButton_ZoomOut.setText(QCoreApplication.translate("cameraScreen", u"\u653e\u5927", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("cameraScreen", u"\u66dd\u5149", None))
        self.label.setText(QCoreApplication.translate("cameraScreen", u"\u66dd\u5149\u6a21\u5f0f:", None))
        self.label_2.setText(QCoreApplication.translate("cameraScreen", u"\u81ea\u52a8\u66dd\u5149:", None))
        self.label_3.setText(QCoreApplication.translate("cameraScreen", u"\u66dd\u5149\u65f6\u95f4:", None))
        self.label_4.setText(QCoreApplication.translate("cameraScreen", u"\u91c7\u96c6\u6570:", None))
        self.label_AcqNum.setText(QCoreApplication.translate("cameraScreen", u"0", None))
        self.label_5.setText(QCoreApplication.translate("cameraScreen", u"FPS:", None))
        self.label_FPS.setText(QCoreApplication.translate("cameraScreen", u"0", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("cameraScreen", u"\u89e6\u53d1", None))
        self.label_6.setText(QCoreApplication.translate("cameraScreen", u"\u89e6\u53d1\u6a21\u5f0f:", None))
        self.label_7.setText(QCoreApplication.translate("cameraScreen", u"\u89e6\u53d1\u6e90:", None))
        self.pushButton_SendSoftwareCommand.setText(QCoreApplication.translate("cameraScreen", u"\u53d1\u9001\u8f6f\u89e6\u53d1\u547d\u4ee4", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("cameraScreen", u"\u589e\u76ca", None))
        self.label_8.setText(QCoreApplication.translate("cameraScreen", u"\u81ea\u52a8\u589e\u76ca:", None))
        self.label_9.setText(QCoreApplication.translate("cameraScreen", u"\u589e\u76ca\u503c:", None))
        self.pushButton.setText(QCoreApplication.translate("cameraScreen", u"\u5173\u95ed", None))
    # retranslateUi

